# Generated by Django 5.2.14 on 2026-05-15 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('curso', models.CharField(choices=[('PRE-KINDER', 'Pre-Kinder'), ('KINDER', 'Kinder'), ('1° BÁSICO', '1° Básico'), ('2° BÁSICO', '2° Básico'), ('3° BÁSICO', '3° Básico'), ('4° BÁSICO', '4° Básico'), ('5° BÁSICO', '5° Básico'), ('6° BÁSICO', '6° Básico'), ('7° BÁSICO', '7° Básico'), ('8° BÁSICO', '8° Básico'), ('I° MEDIO', 'I° Medio'), ('II° MEDIO', 'II° Medio'), ('III° MEDIO', 'III° Medio'), ('IV° MEDIO', 'IV° Medio')], max_length=20)),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('apoderado_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre apoderado')),
                ('apoderado_telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono apoderado')),
                ('apoderado_rut', models.CharField(blank=True, max_length=12, verbose_name='RUT apoderado')),
                ('activo', models.BooleanField(default=True)),
                ('anio', models.PositiveIntegerField(default=2026, verbose_name='Año escolar')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Atraso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('LLEGADA', 'Llegada'), ('RECREO', 'Recreo'), ('ALMUERZO', 'Almuerzo')], default='LLEGADA', max_length=10)),
                ('lugar', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atrasos', to='core.alumno')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atraso',
                'verbose_name_plural': 'Atrasos',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lugar_entregado', models.CharField(choices=[('DIRECCIÓN', 'Dirección'), ('INSPECTORÍA 1ER PISO', 'Inspectoría 1er piso'), ('INSPECTORÍA 2DO PISO', 'Inspectoría 2do piso')], max_length=30, verbose_name='Lugar de entrega')),
                ('retiro', models.CharField(choices=[('AL FINAL DEL DÍA', 'Al final del día'), ('RETIRA APODERADO', 'Retira apoderado'), ('PENDIENTE', 'Pendiente')], default='AL FINAL DEL DÍA', max_length=20)),
                ('aviso_apoderado', models.BooleanField(default=False, verbose_name='¿Aviso a apoderado?')),
                ('observacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celulares', to='core.alumno')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Celular requisado',
                'verbose_name_plural': 'Celulares requisados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ControlUniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('falta', models.CharField(choices=[('SIN UNIFORME', 'Sin uniforme'), ('SIN POLERÓN', 'Sin polerón'), ('SIN POLERA NI POLERÓN', 'Sin polera ni polerón')], max_length=30)),
                ('tiene_uniforme_comprado', models.BooleanField(default=True, verbose_name='¿Tiene uniforme comprado?')),
                ('detalle', models.TextField(blank=True)),
                ('contacto_apoderado', models.CharField(blank=True, max_length=15, verbose_name='Teléfono contacto')),
                ('llamado', models.BooleanField(default=False, verbose_name='¿Se llamó?')),
                ('determinacion', models.CharField(blank=True, max_length=200, verbose_name='Determinación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to='core.alumno')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de uniforme',
                'verbose_name_plural': 'Control de uniformes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(choices=[('ENFERMO/A', 'Enfermo/a'), ('CONTROL MÉDICO', 'Control médico'), ('PERSONAL', 'Personal'), ('TRÁMITES', 'Trámites'), ('ACC. ESCOLAR', 'Accidente escolar'), ('LOCOMOCIÓN', 'Locomoción'), ('FAMILIAR', 'Familiar'), ('PERIODO ADAPTACIÓN', 'Periodo adaptación'), ('DEPORTE', 'Deporte'), ('ENTRENAMIENTO', 'Entrenamiento'), ('ALMUERZO', 'Almuerzo'), ('VIAJE', 'Viaje'), ('TERAPIA', 'Terapia'), ('KINESIÓLOGO', 'Kinesiólogo'), ('OTRO', 'Otro')], max_length=30)),
                ('persona_retira', models.CharField(max_length=200, verbose_name='Persona que retira')),
                ('rut_retira', models.CharField(blank=True, max_length=12, verbose_name='RUT persona que retira')),
                ('observacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='core.alumno')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='VisitaApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('destino', models.CharField(choices=[('INSPECTORÍA GENERAL', 'Inspectoría General'), ('PIE', 'PIE'), ('UTP', 'UTP'), ('PROFESOR/A', 'Profesor/a'), ('CONV. ESCOLAR', 'Convivencia Escolar'), ('DIRECCIÓN', 'Dirección')], max_length=30)),
                ('funcionario', models.CharField(max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita de apoderado',
                'verbose_name_plural': 'Visitas de apoderados',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
