# Generated by Django 5.2.16 on 2026-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alumno",
            index=models.Index(
                fields=["nombre", "apellido", "anio"], name="alumno_busqueda_idx"
            ),
        ),
    ]
