# Generated by Django 5.2.16 on 2026-08-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_index_alumno_busqueda"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="es_campo",
            field=models.BooleanField(default=False, verbose_name="Campo"),
        ),
        migrations.AddField(
            model_name="atraso",
            name="motivo",
            field=models.CharField(
                blank=True, default="ATRASO", max_length=50, verbose_name="Motivo"
            ),
        ),
        migrations.CreateModel(
            name="LlamadaApoderado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                ("detalle", models.TextField(verbose_name="Detalle de la llamada")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llamadas",
                        to="core.alumno",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Llamada a apoderado",
                "verbose_name_plural": "Llamadas a apoderados",
                "ordering": ["-fecha", "-hora"],
            },
        ),
    ]
