# Generated by Django 5.2.17 on 2026-09-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alumno_unico_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_habilitado', models.BooleanField(default=False, verbose_name='Habilitar registro público')),
            ],
            options={
                'verbose_name': 'Configuración de Registro',
                'verbose_name_plural': 'Configuración de Registro',
            },
        ),
    ]
