# Generated by Django 5.2.17 on 2026-10-01 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def marcar_existentes_como_entregados(apps, schema_editor):
    """Las requisas ya registradas son históricas: el teléfono volvió al alumno.

    Se marcan como ENTREGADO para que no aparezcan como pendientes en la lista
    del día. fecha_entrega queda NULL porque no se conoce la fecha real.
    """
    Celular = apps.get_model("core", "Celular")
    Celular.objects.all().update(estado="ENTREGADO")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_acciondisciplinaria_tipo_entrevista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celulares_entregados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='celular',
            name='estado',
            field=models.CharField(choices=[('EN_DIRECCION', 'En poder de la dirección'), ('ENTREGADO', 'Entregado')], default='EN_DIRECCION', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='celular',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='retiro',
            field=models.CharField(choices=[('AL FINAL DEL DÍA', 'Al final del día'), ('RETIRA APODERADO', 'Retira apoderado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20),
        ),
        migrations.RunPython(marcar_existentes_como_entregados, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='celular',
            index=models.Index(fields=['estado', 'fecha'], name='core_celula_estado_28d2e4_idx'),
        ),
    ]
